[package]
name = "ants_code_challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
fastrand = "2.0"


[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
